echo "=== backend/src/input/ ==="
ls /d/Code/moonlight-web-deepseek/backend/src/input/ 2>/dev/null || echo "(not found)"
echo ""
echo "=== backend/src/ ==="
ls -d /d/Code/moonlight-web-deepseek/backend/src/*/ 2>/dev/null || echo "(not found)"
echo ""
echo "=== frontend/js/ ==="
ls /d/Code/moonlight-web-deepseek/frontend/js/ 2>/dev/null || echo "(not found)"
echo ""
echo "=== frontend/js/ui/ ==="
ls /d/Code/moonlight-web-deepseek/frontend/js/ui/ 2>/dev/null || echo "(not found)"
echo ""
echo "=== frontend files containing StreamView ==="
find /d/Code/moonlight-web-deepseek/frontend -name "*StreamView*" 2>/dev/null
find /d/Code/moonlight-web-deepseek/frontend -name "*stream*" 2>/dev/null
echo ""
echo "=== backend streaming/ ==="
ls /d/Code/moonlight-web-deepseek/backend/src/streaming/ 2>/dev/null || echo "(not found)"
echo ""
echo "=== backend files containing mouse ==="
find /d/Code/moonlight-web-deepseek/backend -name "*[Mm]ouse*" -o -name "*[Mm]ouse*" 2>/dev/null