/*
 * MoonlightWeb — TNR suite. Copyright (C) 2026 Bruno Martin.
 * GPLv3 — see repository LICENSE.
 */
import { describe, it, expect } from 'vitest';
import { StreamView } from '../js/ui/StreamView.js';

/**
 * Holding a key has to keep typing.
 *
 * Typematic repeat is generated by the keyboard controller, not by the guest
 * OS, so a key injected with SendInput — the native host's path, and
 * Sunshine's — produces exactly one character however long it stays down. The
 * client's own auto-repeat is therefore the only source of repeat there is, and
 * swallowing it left a key held for two seconds typing a single "v".
 *
 * What must NOT repeat is a press the host never received: the control combos
 * and the clipboard bridge swallow theirs on purpose.
 */

const VK_V = 0x56;
const VK_A = 0x41;

/** Minimal stand-in exposing just what the keyboard path touches. */
function keySink(overrides = {}) {
    const sent = [];
    return {
        sent,
        webrtc: { send: (m) => sent.push(m) },
        _heldPhysKeys: new Map(),
        _metaTapCodes: new Set(),
        _appleKeyboard: false,
        _quitting: false,
        _pendingClipboardWrite: null,
        _kbdCapture: null,
        _locksSynced: true,
        _cssFullscreen: false,
        _clipboardEnabled: false,
        _layoutMap: null,
        _gamingMode: false,
        _pendingPasteKey: null,
        _suppressPasteKeyUpCode: null,
        handleKeyDown: StreamView.prototype.handleKeyDown,
        handleKeyUp: StreamView.prototype.handleKeyUp,
        _sendKeyEvent: StreamView.prototype._sendKeyEvent,
        _forgetHeldKey: StreamView.prototype._forgetHeldKey,
        _holdsThroughStall: StreamView.prototype._holdsThroughStall,
        // Not exercised here, but the clipboard bridge arms a 150ms timer that
        // reaches for them after the test that swallows a paste chord ends.
        _releaseHeldMeta: StreamView.prototype._releaseHeldMeta,
        _releaseKeysHeldUnderMeta: StreamView.prototype._releaseKeysHeldUnderMeta,
        _sendPendingPasteKey: StreamView.prototype._sendPendingPasteKey,
        ...overrides,
    };
}

/** A KeyboardEvent-shaped plain object, as in macMetaKeys.test.js. */
function ev(code, key, mods = {}) {
    return {
        target: {},
        code,
        key,
        keyCode: 0,
        repeat: false,
        ctrlKey: false,
        shiftKey: false,
        altKey: false,
        metaKey: false,
        preventDefault() {},
        ...mods,
    };
}

describe('auto-repeat on a held key', () => {
    it('forwards each repeat, so holding a key types more than one character', () => {
        const v = keySink();
        v.handleKeyDown(ev('KeyV', 'v'));
        v.handleKeyDown(ev('KeyV', 'v', { repeat: true }));
        v.handleKeyDown(ev('KeyV', 'v', { repeat: true }));

        expect(v.sent.map((m) => [m.type, m.keyCode])).toEqual([
            ['keydown', VK_V],
            ['keydown', VK_V],
            ['keydown', VK_V],
        ]);
        // Still one key, still held: the repeats are re-presses, not new keys.
        expect(v._heldPhysKeys.size).toBe(1);

        v.handleKeyUp(ev('KeyV', 'v'));
        expect(v.sent[3]).toMatchObject({ type: 'keyup', keyCode: VK_V });
        expect(v._heldPhysKeys.size).toBe(0);
    });

    it('repeats the physical position, not whatever keyCode the browser reports', () => {
        // AZERTY: the key printed A sits at the QWERTY Q position, and the whole
        // protocol is positional — a repeat must not drift to another key.
        const v = keySink();
        v.handleKeyDown(ev('KeyQ', 'a'));
        v.handleKeyDown(ev('KeyQ', 'a', { repeat: true }));

        expect(v.sent[1]).toMatchObject({ type: 'keydown', keyCode: 0x51, code: 'KeyQ' });
    });

    it('carries the modifiers held at the moment of the repeat', () => {
        const v = keySink();
        v.handleKeyDown(ev('KeyA', 'a'));
        v.handleKeyDown(ev('KeyA', 'A', { repeat: true, shiftKey: true }));

        expect(v.sent[1]).toMatchObject({ type: 'keydown', keyCode: VK_A, shiftKey: true });
    });

    it('says nothing when the press itself was never forwarded', () => {
        // The clipboard bridge swallows Ctrl+V while it waits for the browser's
        // own 'paste' event. Repeating it would ask the host to paste on a key
        // it never saw go down.
        const v = keySink({ _clipboardEnabled: true });
        v.handleKeyDown(ev('KeyV', 'v', { ctrlKey: true }));
        expect(v.sent).toEqual([]);

        v.handleKeyDown(ev('KeyV', 'v', { ctrlKey: true, repeat: true }));
        expect(v.sent).toEqual([]);
    });

    it('ignores a repeat for a key the host does not hold', () => {
        const v = keySink();
        v.handleKeyDown(ev('KeyA', 'a', { repeat: true }));
        expect(v.sent).toEqual([]);
    });
});
