/*
 * MoonlightWeb — browser-based Sunshine/GameStream client.
 * Copyright (C) 2026 Bruno Martin <brunoocto@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Force stereo Opus decoding in the SDP answer.
 *
 * libwebrtc (Chrome/Edge/Firefox) instantiates a MONO Opus decoder unless the
 * negotiated fmtp carries `stereo=1` (RFC 7587 defaults to mono). The stereo
 * Sunshine stream is then downmixed (L+R)/2 by libopus — perceived ~-6 dB
 * quieter than moonlight-qt/Parsec, and the stereo image is lost. The backend
 * offers `stereo=1;sprop-stereo=1`, but browsers do NOT echo those params in
 * their answer, and the receive-side decoder is built from the local (answer)
 * parameters — so the answer must be munged before setLocalDescription.
 *
 * @param {string} sdp - The SDP answer generated by createAnswer().
 * @returns {string} The SDP with `stereo=1;sprop-stereo=1` on the Opus fmtp.
 */
export function forceOpusStereo(sdp) {
    if (typeof sdp !== 'string') return sdp;

    // Find the Opus payload type from the rtpmap line.
    const rtpmap = sdp.match(/^a=rtpmap:(\d+)\s+opus\/48000(?:\/2)?\s*$/im);
    if (!rtpmap) return sdp;
    const pt = rtpmap[1];

    // Append to the existing fmtp line ([^\r\n] keeps the CR out of the match).
    const fmtpRe = new RegExp('^a=fmtp:' + pt + ' [^\\r\\n]*', 'm');
    if (fmtpRe.test(sdp)) {
        return sdp.replace(fmtpRe, (line) =>
            /stereo=/.test(line) ? line : line + ';stereo=1;sprop-stereo=1',
        );
    }

    // No fmtp line for Opus: add one right after its rtpmap.
    const rtpmapRe = new RegExp('^a=rtpmap:' + pt + ' [^\\r\\n]*', 'm');
    return sdp.replace(rtpmapRe, (line) => line + '\r\na=fmtp:' + pt + ' stereo=1;sprop-stereo=1');
}
