#pragma once

#include <QObject>
#include <QMap>
#include <QSet>
#include <QTimer>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QSettings>
#include <QJsonArray>

#include "NvComputer.h"
#include "NvHTTP.h"
#include "../common/Types.h"

class NvPairingManager;

// Forward declarations for qmdnsengine
namespace QMdnsEngine {
    class Server;
    class Browser;
    class Service;
}

class MdnsPendingComputer;

class ComputerManager : public QObject
{
    Q_OBJECT

public:
    explicit ComputerManager(QObject* parent = nullptr);
    ~ComputerManager();

    // Lifecycle
    void init();

    // REST API methods
    QJsonArray getHostsJson() const;
    void handleScanRequest();
    std::pair<int, QJsonObject> handleAddManualHost(const QString& address);
    std::pair<int, QJsonObject> handleDeleteHost(const QString& uuid);

    // Pairing — client generates PIN, user enters it in Sunshine
    std::pair<int, QJsonObject> handleStartPairing(const QString& uuid);
    std::pair<int, QJsonObject> handleSubmitPin(const QString& uuid);

    // App list — HTTPS fetch from paired host, async
    void handleGetAppList(const QString& uuid, ResponseCallback respond);

    // Box art — proxy PNG from Sunshine, async (fetches on demand if not cached)
    void handleGetBoxArt(const QString& uuid, int appId, ResponseCallback respond);

    // Unique client ID, persisted in QSettings
    static QString clientUniqueId();

signals:
    void hostsChanged();
    void scanCompleted();
    void hostAddCompleted(bool success, const QString& error, const QString& uuid);

private slots:
    void onPollTick();
    void onPollReplyFinished();

    // mDNS
    void onMdnsServiceAdded(const QMdnsEngine::Service& service);
    void onMdnsResolved(MdnsPendingComputer* computer, const QVector<QHostAddress>& addresses);

private:
    void loadHosts();
    void saveHosts();
    void startPolling();
    void startMdnsDiscovery();
    NvComputer* findHostByUuid(const QString& uuid) const;
    void addOrUpdateHost(const QString& serverInfo, const NvAddress& addr);
    void tryAddHostFromAddress(const NvAddress& addr, bool fromMdns, const QString& name = QString());

    QMap<QString, NvComputer*> m_Hosts;  // uuid → host, all pointers owned here

    QTimer* m_PollTimer = nullptr;
    QNetworkAccessManager* m_Nam = nullptr;
    NvHTTP* m_Http = nullptr;

    // Pending poll tracking: reply → uuid
    QMap<QNetworkReply*, QString> m_PendingPolls;

    // HTTPS pair verification via /applist for paired hosts
    QMap<QString, QDateTime> m_LastPairCheck;
    QSet<QString> m_PendingPairChecks;  // uuid of hosts being verified
    void onPairCheckFinished();

    // Active pairing sessions: uuid → PairingManager
    QMap<QString, NvPairingManager*> m_ActivePairings;
    QMap<QString, QString> m_PairingPins;  // uuid → PIN (generated by client)

    // Box art cache: uuid -> (appId -> pngData)
    QMap<QString, QMap<int, QByteArray>> m_BoxArtCache;

    // In-flight box art requests: uuid -> (appId -> list of pending callbacks)
    QMap<QString, QMap<int, QList<ResponseCallback>>> m_PendingBoxArtCallbacks;

    // Serialize HTTPS box art fetches per host (only one at a time)
    QSet<QString> m_ActiveBoxArtFetches;       // hosts with an active fetch
    QMap<QString, QList<int>> m_BoxArtFetchQueue;  // per-host queue of appIds

    // Prevent overlapping mDNS scans
    QDateTime m_LastScanTime;

    void enqueueBoxArtFetch(const QString& uuid, int appId);
    void startBoxArtFetch(const QString& uuid, int appId);
    void onBoxArtFetchComplete(const QString& uuid, int appId, bool ok);
    void fetchNextBoxArtInBackground(const QString& uuid);

    // mDNS state
    QMdnsEngine::Server* m_MdnsServer = nullptr;
    QMdnsEngine::Browser* m_MdnsBrowser = nullptr;
    QList<MdnsPendingComputer*> m_PendingResolutions;
    bool m_MdnsActive = false;
};
