#pragma once

#include <QObject>
#include <QMap>
#include <QSet>
#include <QTimer>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QSettings>
#include <QJsonArray>

#include "NvComputer.h"
#include "NvHTTP.h"

class NvPairingManager;

// Forward declarations for qmdnsengine
namespace QMdnsEngine {
    class Server;
    class Browser;
    class Service;
}

class MdnsPendingComputer;

class ComputerManager : public QObject
{
    Q_OBJECT

public:
    explicit ComputerManager(QObject* parent = nullptr);
    ~ComputerManager();

    // Lifecycle
    void init();

    // REST API methods
    QJsonArray getHostsJson() const;
    void handleScanRequest();
    void handleAddManualHost(const QString& address);

    // Pairing — client generates PIN, user enters it in Sunshine
    std::pair<int, QJsonObject> handleStartPairing(const QString& uuid);
    std::pair<int, QJsonObject> handleSubmitPin(const QString& uuid);

    // Unique client ID, persisted in QSettings
    static QString clientUniqueId();

signals:
    void hostsChanged();
    void scanCompleted();
    void hostAddCompleted(bool success, const QString& error, const QString& uuid);

private slots:
    void onPollTick();
    void onPollReplyFinished();

    // mDNS
    void onMdnsServiceAdded(const QMdnsEngine::Service& service);
    void onMdnsResolved(MdnsPendingComputer* computer, const QVector<QHostAddress>& addresses);

private:
    void loadHosts();
    void saveHosts();
    void startPolling();
    void startMdnsDiscovery();
    NvComputer* findHostByUuid(const QString& uuid) const;
    void addOrUpdateHost(const QString& serverInfo, const NvAddress& addr);
    void tryAddHostFromAddress(const NvAddress& addr, bool fromMdns, const QString& name = QString());

    QMap<QString, NvComputer*> m_Hosts;  // uuid → host, all pointers owned here

    QTimer* m_PollTimer = nullptr;
    QNetworkAccessManager* m_Nam = nullptr;
    NvHTTP* m_Http = nullptr;

    // Pending poll tracking: reply → uuid
    QMap<QNetworkReply*, QString> m_PendingPolls;

    // Active pairing sessions: uuid → PairingManager
    QMap<QString, NvPairingManager*> m_ActivePairings;
    QMap<QString, QString> m_PairingPins;  // uuid → PIN (generated by client)

    // mDNS state
    QMdnsEngine::Server* m_MdnsServer = nullptr;
    QMdnsEngine::Browser* m_MdnsBrowser = nullptr;
    QList<MdnsPendingComputer*> m_PendingResolutions;
    bool m_MdnsActive = false;
};
